import { CompanyAccount, Product, Order, Campaign } from "./types";

export const initialCompany: CompanyAccount = {
  id: "comp_01",
  name: "متجر رواء للعطور الفاخرة",
  category: "عطور ومستحضرات تجميل",
  ownerName: "أحمد الحارثي",
  email: "ahmed@rowaa-oud.om",
  phone: "+968 9123 4567",
  currency: "OMR / $",
  plan: "partner",
  commissionRate: 5, // 5% profit share on AI closed sales
  agentName: "سارة — مستشارة رواء الذكية",
  agentDialect: "omani",
  agentAutoDiscountMax: 10,
  whatsappConnected: true,
  whatsappNumber: "+968 9123 4567",
};

export const sampleDemoCompanies: CompanyAccount[] = [
  initialCompany,
  {
    id: "comp_02",
    name: "شركة نماء للإلكترونيات الذكية",
    category: "إلكترونيات وأجهزة منزلية",
    ownerName: "سالم المعمري",
    email: "salem@namaa-tech.om",
    phone: "+968 9888 1234",
    currency: "OMR / $",
    plan: "partner",
    commissionRate: 5,
    agentName: "فهد — مهندس مبيعات نماء",
    agentDialect: "gulf",
    agentAutoDiscountMax: 8,
    whatsappConnected: true,
    whatsappNumber: "+968 9888 1234",
  },
  {
    id: "comp_03",
    name: "ماركة سدرة للأزياء العصرية",
    category: "أزياء وعبايات راقية",
    ownerName: "مريم البلوشية",
    email: "maryam@sidra-fashion.om",
    phone: "+968 9777 6543",
    currency: "OMR / $",
    plan: "starter",
    commissionRate: 0,
    agentName: "ريما — منسقة إطلالات سدرة",
    agentDialect: "omani",
    agentAutoDiscountMax: 5,
    whatsappConnected: true,
    whatsappNumber: "+968 9777 6543",
  },
];

export const initialProducts: Product[] = [
  {
    id: "prod_01",
    name: "عطر ميسان الملكي (نسخة العود الفاخر)",
    category: "عطور شرقية",
    price: 34,
    cost: 11,
    stock: 85,
    image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&auto=format&fit=crop&q=80",
    description: "مزيج ملكي ساحر من دهن العود الكمبودي المعتق، والورد الطائفي، ولمسات من العنبر الفاخر مع ثبات يتجاوز 48 ساعة.",
    sellingPoints: [
      "ثبات وفوحان فائق يدوم لأكثر من 48 ساعة",
      "علبة خشبية فاخرة مخملية مناسبة للإهداء الراقي",
      "ضمان ذهبي للاسترجاع الفوري في حال لم يعجبك العطر",
      "شحن مجاني وسريع لكافة ولايات السلطنة ودول الخليج",
    ],
    aiTrainingNotes: "إذا سأل العميل عن الثبات، أكد له أنه يدوم يومين ومجرب، وإذا طلب خصم لأكثر من حبة اعرض له كود MAYSAN10 لخصم 10% فوراً.",
    warranty: "ضمان ذهبي 14 يوماً مع استرجاع كامل",
    deliveryTime: "24-48 ساعة",
    salesCount: 164,
    isActive: true,
  },
  {
    id: "prod_02",
    name: "مجموعة لبان الحوجري الملكي الفاخر (البخور والزيت)",
    category: "بخور وعناية",
    price: 22,
    cost: 7,
    stock: 120,
    image: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&auto=format&fit=crop&q=80",
    description: "أجود أنواع اللبان الحوجري العماني الأصلي من جبال ظفار، منقى يدويًا بجودة فريدة مع زيت اللبان النقي المركز.",
    sellingPoints: [
      "لبان حوجري أخضر نقي 100% من صلالة",
      "معطر طبيعي للجو ومعقم ذو رائحة زكية مهدئة",
      "يشمل مبخرة كرستالية فاخرة مجانية",
    ],
    aiTrainingNotes: "أخبر العميل أنه لبان أصلي قطاف هذا الموسم ومناسب جداً للتبخير اليومي وإهداء الضيوف.",
    warranty: "ضمان جودة وأصالة المنتج 100%",
    deliveryTime: "24-48 ساعة",
    salesCount: 218,
    isActive: true,
  },
  {
    id: "prod_03",
    name: "خمرية رواء الخاصة للشعر والجسم",
    category: "عناية وعطور",
    price: 15,
    cost: 4.5,
    stock: 64,
    image: "https://images.unsplash.com/photo-1547887537-6158d64c35b3?w=600&auto=format&fit=crop&q=80",
    description: "تركيبة غنية خالية من الكحول بزيوت طبيعية ترطب الشعر وتعطره برائحة المسك الأبيض والزهور الربيعية.",
    sellingPoints: [
      "خالية تماماً من الكحول ومناسبة للشعر الحساس",
      "رائحة تدوم بعد الاستحمام ليوم كامل",
      "ملمس حريري بدون تزييت",
    ],
    aiTrainingNotes: "وضح للعميلة أن المنتج آمن تماماً على الشعر المصبوغ والمعالج بالبروتين.",
    warranty: "ضمان رضا العميل",
    deliveryTime: "24-48 ساعة",
    salesCount: 95,
    isActive: true,
  },
];

export const initialOrders: Order[] = [
  {
    id: "ORD-9482",
    customerName: "سيف بن سالم العامري",
    customerPhone: "+968 9912 3456",
    city: "مسقط (السيب)",
    address: "الموالح الجنوبية، بالقرب من جامع الصادق الأمين",
    productId: "prod_01",
    productName: "عطر ميسان الملكي (نسخة العود الفاخر)",
    quantity: 2,
    totalAmount: 61.2, // applied 10% discount by AI
    paymentMethod: "cash_on_delivery",
    status: "confirmed_by_ai",
    createdAt: "منذ 14 دقيقة",
    aiConversationSnippet: "العميل سأل عن التوصيل للسيب والخصم، الوكيل عرض كود MAYSAN10 وثبت العنوان ورقم الهاتف خلال دقيقتين فقط.",
    source: "whatsapp_ai",
  },
  {
    id: "ORD-9481",
    customerName: "خالد المعمري",
    customerPhone: "+968 9455 7890",
    city: "صحار",
    address: "الهمبار، شارع المنتزه، فيلا 42",
    productId: "prod_02",
    productName: "مجموعة لبان الحوجري الملكي الفاخر",
    quantity: 1,
    totalAmount: 22.0,
    paymentMethod: "cash_on_delivery",
    status: "shipped",
    createdAt: "منذ 42 دقيقة",
    aiConversationSnippet: "استفسر عن أصالة اللبان وكيفية الاستخدام، الوكيل أرسل فيديو الشرح وأكد موعد الاستلام غداً.",
    source: "whatsapp_ai",
  },
  {
    id: "ORD-9480",
    customerName: "مها الزعابية",
    customerPhone: "+968 9234 1122",
    city: "صلالة",
    address: "حي السعادة، مجمع الفخامة",
    productId: "prod_01",
    productName: "عطر ميسان الملكي (نسخة العود الفاخر)",
    quantity: 1,
    totalAmount: 34.0,
    paymentMethod: "online_link",
    status: "delivered",
    createdAt: "أمس، 08:30 م",
    aiConversationSnippet: "العميلة طلبت رابط الدفع ببطاقة بنك مسقط، الوكيل أرسل بوابة الدفع وأصدر الفاتورة فورياً.",
    source: "meta_ad_instagram",
  },
  {
    id: "ORD-9479",
    customerName: "محمد الهاشمي",
    customerPhone: "+968 9876 5432",
    city: "نزوى",
    address: "فرق، بجوار اللولو هايبرماركت",
    productId: "prod_03",
    productName: "خمرية رواء الخاصة للشعر والجسم",
    quantity: 3,
    totalAmount: 40.5,
    paymentMethod: "cash_on_delivery",
    status: "delivered",
    createdAt: "أمس، 04:15 م",
    aiConversationSnippet: "تم إغلاق البيع وإضافة عرض هدية مجانية مع الـ 3 قطع بنجاح.",
    source: "whatsapp_ai",
  },
];

export const initialCampaigns: Campaign[] = [
  {
    id: "camp_01",
    name: "حملة فيديو UGC — عطر ميسان الملكي (إنستغرام ريلز)",
    platform: "instagram",
    status: "active",
    dailyBudget: 25,
    spent: 345,
    revenue: 1680,
    roas: 4.87,
    clicks: 1420,
    orders: 49,
    targetAudience: "رجال وسيدات 24-48 سنة | سلطنة عمان والإمارات | اهتمامات: عطور فاخرة، عود، تسوق",
    creativeType: "UGC Video Reel",
  },
  {
    id: "camp_02",
    name: "حملة لبان الحوجري الظفاري — إعلانات فيسبوك وإنستغرام",
    platform: "both",
    status: "active",
    dailyBudget: 15,
    spent: 210,
    revenue: 890,
    roas: 4.23,
    clicks: 980,
    orders: 40,
    targetAudience: "سيدات ورجال 22-55 سنة | اهتمامات: بخور، ديكور منزلي، هدايا راقية",
    creativeType: "Carousel Showcase",
  },
  {
    id: "camp_03",
    name: "إعادة استهداف زوار المتجر والواتساب المترددين (Retargeting)",
    platform: "both",
    status: "active",
    dailyBudget: 10,
    spent: 120,
    revenue: 610,
    roas: 5.08,
    clicks: 450,
    orders: 22,
    targetAudience: "الزوار الذين تواصلوا ولم يكملوا بيانات الشحن خلال آخر 14 يوماً",
    creativeType: "Story Direct Ad",
  },
];
