ALTER TABLE "Product" ADD COLUMN "shippingFee" REAL NOT NULL DEFAULT 1.5;
ALTER TABLE "Order" ADD COLUMN "shippingFeeCharged" REAL NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN "shippingPrepaidAt" DATETIME;
