ALTER TABLE "Product" ADD COLUMN "shippingFee" DOUBLE PRECISION NOT NULL DEFAULT 1.5;
ALTER TABLE "Order" ADD COLUMN "shippingFeeCharged" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN "shippingPrepaidAt" TIMESTAMP(3);
